# Generated by Django 3.2.4 on 2021-06-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='lunch_duration',
            field=models.IntegerField(help_text='*время в минутах', verbose_name='Длительность обеда'),
        ),
    ]
