# Generated by Django 3.2.4 on 2021-06-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210621_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='duration',
            field=models.TimeField(verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_duration',
            field=models.TimeField(verbose_name='Интервал конца обеда'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='max_duration',
            field=models.TimeField(verbose_name='Максимальная длительность'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(verbose_name='Начало смены'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_duration',
            field=models.TimeField(verbose_name='Интервал начала обеда'),
        ),
    ]
