# Generated by Django 3.2.4 on 2021-06-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0002_alter_shift_lunch_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=25, verbose_name='Название')),
                ('norma_hours', models.FloatField(default=0.0, verbose_name='Норма часов')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договоров',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=25, verbose_name='Канал связи')),
            ],
            options={
                'verbose_name': 'Канал связи',
                'verbose_name_plural': 'Каналы связи',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25, verbose_name='Роль')),
                ('role_time', models.FloatField(default=0.0, verbose_name='Время на роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=25, verbose_name='Часовой пояс')),
                ('utc', models.IntegerField(default=5, verbose_name='UTC')),
            ],
            options={
                'verbose_name': 'Часовой пояс',
                'verbose_name_plural': 'Часовые пояса',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=25, verbose_name='Отчество')),
                ('employment_date', models.DateField(verbose_name='Дата трудоустройства')),
                ('dismissal_date', models.DateField(blank=True, verbose_name='Дата увольнения')),
                ('transition_history', models.JSONField(blank=True, verbose_name='История переходов')),
                ('person_priority', models.IntegerField(default=1, verbose_name='Индекс в графике')),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.contracttype', verbose_name='Тип договора')),
                ('link_channels', models.ManyToManyField(to='structure.Link', verbose_name='Каналы связи')),
                ('roles', models.ManyToManyField(to='structure.Role', verbose_name='Роли')),
                ('shift_templates', models.ManyToManyField(blank=True, to='schedule.Shift', verbose_name='Шаблоны графика')),
                ('timezone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.timezone')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
    ]
