# Generated by Django 3.2.4 on 2021-06-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.contracttype', verbose_name='Тип договора'),
        ),
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, to='structure.Role', verbose_name='Роли'),
        ),
    ]
