# Generated by Django 3.2.4 on 2021-06-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20210618_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dismissal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
    ]
