# Generated by Django 3.2.4 on 2021-06-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_person_dismissal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='transition_history',
            field=models.JSONField(blank=True, null=True, verbose_name='История переходов'),
        ),
    ]
