# Generated by Django 3.2.4 on 2021-07-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_auto_20210629_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='patronymic',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество'),
        ),
    ]
