# Generated by Django 3.2.4 on 2021-07-06 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_alter_person_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, verbose_name='Название типа')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='timezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.timezone', verbose_name='Часовой пояс'),
        ),
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.teamtype', verbose_name='Тип команды'),
        ),
    ]
