# Generated by Django 3.2.4 on 2021-07-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_auto_20210706_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtype',
            options={'verbose_name': 'Тип команды', 'verbose_name_plural': 'Типы команд'},
        ),
    ]
